In [38]:
%matplotlib inline

In [5]:
import torch
##performed pip install torch

In [4]:
import torch
##Tensor API Walkthrough
##similar to the idea of ndarrays

In [3]:
import numpy as np
##importing

In [6]:
##Tensor_Initialization

In [32]:
data = [[1,2,3],[4,5,6],[7,8,9]]

In [33]:
print(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [28]:
t_data = torch.tensor(data)
##initializing or creating directly from the 
##torch.tensor() is a multidimensional matrix containing elements of same data type

In [36]:
print(t_data)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [29]:
##tensor can be created from NumPy arrays and NumPy array can be created from tensors

In [30]:
np_array = np.array(data)

In [77]:
print(np_array)


[[ 16  32  48]
 [ 64  80  96]
 [112 128 144]]


In [78]:
np_array = np.array(data)

In [73]:
t_data = torch.tensor(data)

In [74]:
numpy_array = torch.from_numpy(np_array)
##In the above, np_array and numpy_array shares the same address location
##change in one will change the value of another

In [69]:
##print ndarrays

In [75]:
print(f"values in numpy tensor array: \n{numpy_array}")

values in numpy tensor array: 
tensor([[ 16,  32,  48],
        [ 64,  80,  96],
        [112, 128, 144]])


In [71]:
print(f"Values in np array: \n{np_array}\n")

Values in np array: 
[[ 8 16 24]
 [32 40 48]
 [56 64 72]]



In [72]:
np.multiply(np_array,2, out = np_array)

array([[ 16,  32,  48],
       [ 64,  80,  96],
       [112, 128, 144]])

In [76]:
print(f"2 X Values of array initialized with tensor\n{numpy_array}\n")

2 X Values of array initialized with tensor
tensor([[ 16,  32,  48],
        [ 64,  80,  96],
        [112, 128, 144]])



In [79]:
test = [[9,12,11],[5,10,55]]

In [80]:
np_test = np.array(test) 

In [81]:
tensor_test = torch.tensor(test)

In [85]:
numpy_test = torch.from_numpy(np_test)

In [86]:
print(f"\n{numpy_test}\n")


tensor([[ 9, 12, 11],
        [ 5, 10, 55]])



In [87]:
print(f"\n{np_test}\n")


[[ 9 12 11]
 [ 5 10 55]]



In [88]:
print(f"\n{tensor_test}\n")


tensor([[ 9, 12, 11],
        [ 5, 10, 55]])



In [89]:
np_test = np.multiply(np_test, 2, out = np_test)

In [90]:
print(f"\n{np_test}\n")


[[ 18  24  22]
 [ 10  20 110]]



In [91]:
print(f"\n{numpy_test}\n")


tensor([[ 18,  24,  22],
        [ 10,  20, 110]])



In [92]:
numpy_test_ones = torch.ones_like(numpy_test)

In [93]:
print("{numpy_test_ones}")

{numpy_test_ones}


In [94]:
print("\n{numpy_test_ones}\n")


{numpy_test_ones}



In [95]:
print(f"\n{numpy_test_ones}\n")


tensor([[1, 1, 1],
        [1, 1, 1]])



In [96]:
numpy_test_ones = torch.ones_like(numpy_test)

In [97]:
print(f"\n{numpy_test_ones}\n")


tensor([[1, 1, 1],
        [1, 1, 1]])



In [99]:
numpy_test_rand = torch.rand_like(numpy_test, dtype = torch.float)

In [100]:
print(f"\n{numpy_test_rand}\n")


tensor([[0.9352, 0.8926, 0.2191],
        [0.3292, 0.5328, 0.9129]])



In [102]:
##Tensor defined by a shape
##Tensors of constant value
## where shape - a tuple is an argument

In [103]:
shape = (3,3)

In [104]:
rand_tensor = torch.rand(shape)

In [105]:
print(f"\n{rand_tensor}\n")


tensor([[0.7333, 0.7434, 0.2898],
        [0.6578, 0.7246, 0.3715],
        [0.1257, 0.5487, 0.2145]])



In [106]:
ones_tensor = torch.ones(shape)

In [107]:
print(f"\n{ones_tensor}\n")


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])



In [109]:
zero_tensor = torch.zeros(shape)

In [111]:
print(f"\n{zero_tensor}\n")


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

